### PR TITLE
Fix some type specs

### PR DESCRIPTION
**Pull request by binarin**
I've touched only those types as I'm trying to make dialyzer completely happy
with `rabbitmq_autocluster`.

### CODE REVIEW

**Comment by gmr** [comment]
Thanks!

**Comment by binarin** [comment]
Could you please tag this version? I'm going to fix all dialyzer warnings in rabbitmq-autocluster, and I need somehow reference this fix.

**Comment by gmr** [comment]
Sure, I'll try and get on this tonight.

**Comment by gmr** [comment]
https://github.com/gmr/rabbitmq-aws/releases/tag/0.1.3

**Pull request merged**
